### ISSUE TITLE
Allow accept self-certificate

### ISSUE THREAD

**Issue by abertranb** [arantes555/electron-fetch#13]
Hi is possible to do that?
We can enable request instead of  useElectronNet
Then we can do something like:
```
var Client = require('node-rest-client').Client; 
var client = new Client();
var args = {
	headers: { "Content-Type": "application/json",  'Authorization': '' },
	data:{},
	rejectUnauthorized: false
};
```

Thanks!

**Comment by arantes555** [comment]
@abertranb you can do this directly with electron : https://electronjs.org/docs/api/app#event-certificate-error

You can basically just do:
```javascript
app.on('certificate-error', (event, webContents, url, error, certificate, callback) => {
  if (url === 'https://github.com') {
    // Verification logic.
    event.preventDefault()
    callback(true)
  } else {
    callback(false)
  }
})

```

**Comment by abertranb** [comment]
Hi I tested and using useElectronNet to false raises
failed, reason: self signed certificate in certificate chain',
  type: 'system',
  errno: 'SELF_SIGNED_CERT_IN_CHAIN',
  code: 'SELF_SIGNED_CERT_IN_CHAIN' }

And didn't stop on breakpoint on certificate-error
Using electronNet then I don't have an answer I wait fir response and nothing,,,

Could be an isue with remote server? any idea?

thanks

**Comment by abertranb** [comment]
Fixed with
```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
```
