### ISSUE TITLE
body value is "[object Object]"

### ISSUE THREAD

**Issue by Nathan961207** [arantes555/electron-fetch#14]
Hi,
I cannot access properties inside the body value.

I used the get method like this: 

  
      export const getInstrument = async () => {
       const url = baseUrl + "/Instruments";
       const res = await fetch(url, {
         method: "GET",
         headers: { "Content-Type": "application/json" }
       });

       return await res;
     }; 
     
I get the following response when checking the debug console

![image](https://user-images.githubusercontent.com/15314334/56199000-4d23b200-603c-11e9-966d-2ce19b9db67e.png)

If use res.json() i get the following error 

    Uncaught (in promise) SyntaxError: Unexpected token o in JSON at position 1
        at Object.parse (<anonymous>)

**Comment by arantes555** [comment]
1. It is totally normal that your first attempt doesn't work. Like all fetch, you have to call methods on the response object to get the response content.

2. I see you tried one on these methods, the `.json()`. If it gives this error, it means that the server just does not respond with a correct JSON. You can try `.text()` to see exactly what the servers responds.

3. From your screenshot, you appear to be using it in a browser window. This is really not the purpose of electron-fetch, and there is very little to gain in using in in a browser window, where you can simply use the original `window.fetch`. The goal of electron-fetch is to provide a similar interface but for electron's background.

**Comment by Nathan961207** [comment]
Hi,
The `.text()` method returns "[object Object]". 
I did get it to work using the built-in fetch.  

Thanks.

**Comment by arantes555** [comment]
@Nathan961207 I'm curious as to what was that API ? If you get `[object Object]` when using `.text()`, it should indicate an error with the server, so I don't understand how it could work with the built-in fetch either. This could indeed indicate a bug with electron-fetch, so I'd be grateful for a bit more info on the matter. Thanks !

**Comment by Nathan961207** [comment]
@arantes555 The server is fine, the only reason i used electron-fetch was because when i sent POST requests using the built in fetch i wasn´t allowed due to cors issues on the apache server.  

I expected the GET request to also work, it does but just unwrapping the object does not seem to work.

What kind of information do you need? I would be happy to help.

**Comment by arantes555** [comment]
@Nathan961207 The most helpful would be a test-case, a.k.a. a git repo with a minimal server code to be able to reproduce the issue, and minimal client code that succeeds with regular fetch and gives the error you described with electron-fetch.

**Comment by Nathan961207** [comment]
Hi sorry for the late reply,
I can provide server code but it is an as400 machine using RPGLE as language, not too many people have one of those lying around.

The client code that gives the error is provided already, the success code that I am using now: 

    export const getInstruments = async () => {
     const url = baseUrl + "/Instruments";
      return await fetch(url);
    };

**Comment by tex0l** [comment]
Hello @Nathan961207,
Indeed, we don't have an AS400 lying around :).

To sum up your test case:
* You import `electron-fetch` in the context of an `electron` `BrowserWindow`;
* You attempt to do a `.json()` on a well-formatted `GET` response you got from this request:
```
export const getInstruments = async () => {
 const url = baseUrl + "/Instruments";
  return await fetch(url);
};
```
* You attempt to do a `.text()` on this response and it gives you `[object Object]`.

Is that right? The most important items we'd need to help you debug this are:
* your exact electron version;
* the exact code importing `electron-fetch` and doing the request;
* Are you able to reproduce the bug with another URL ? For example using  `'https://jsonplaceholder.typicode.com/todos/1'` which is a fake online API for testing. It'd be very helpful if you could make a minimal test-case to reproduce your bug on our end like @arantes555 suggested.

The fact that you get `[object Object]`  with `response.text()` is apparently a bug, it shouldn't happen except if the actual text of the response is `"[object Object]"`. I suspect an IPC bug.

**Comment by Nathan961207** [comment]
Yes, that is correct.
I am also using react inside electron [https://medium.com/@kitze/%EF%B8%8F-from-react-to-an-electron-app-ready-for-production-a0468ecb1da3](url)
- electron v4.1.4
- the url you provided gave the same error(perhaps react is the issue?)

Here is the code i am using      
```javascript
componentDidMount() {
    this.mounted = true;
    if (this.mounted) {
      getInstruments()
        .then(resp => {
          if (resp.ok) {
            resp.json().then(dataset => {
              this.setState({ data: dataset.response });
            });
          } else {
            this.handleSnackClick("error", "Error, something went wrong");
          }
        })
        .catch(err => {
          this.handleSnackClick("error", "Error, something went wrong");
        });
    }
  }
```

**Comment by nEdAy** [comment]
Why closed, I had the same error. Use 'https://jsonplaceholder.typicode.com/todos/1' also gave "[object Object]"

**Comment by nEdAy** [comment]
"dependencies": {
    "electron-fetch": "^1.4.0",
    "electron-is-dev": "^1.1.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-scripts": "3.2.0"
  },
  "devDependencies": {
    "concurrently": "^5.0.0",
    "electron": "^6.1.5",
    "electron-builder": "^21.2.0",
    "wait-on": "^3.3.0"
  }

**Comment by arantes555** [comment]
@nEdAy To see what's going on, the perfect thing would be a code example. I cannot check any further without code I can run myself and tweak.

**Comment by nunong21** [comment]
Yeap, don't know why this was closed, after 4 years, I'm also getting this same error, both with  await response.text() and .json()

**Comment by arantes555** [comment]
@nunong21 I cannot reproduce the issue. Can you provide an example of a reproduction in a code repository, so I can run it to check what is going on ?

**Comment by nunong21** [comment]
If you don't mind, could you take a look at the following repo?
https://github.com/nunong21/rf-tickets/blob/master/src/renderer/src/context/ProductsCartContext.tsx#L61

I get that ` [Object Object] `  when I do both `console.log(result.json())` and `console.log(result.text())`
