### ISSUE TITLE
is there a way to use the same connection object while fetching multiple files from the same host ?

### ISSUE THREAD

**Issue by btargac** [arantes555/electron-fetch#15]
While reading curl manual I came up with these sentences 

> curl  will  attempt  to re-use connections for multiple file transfers, so that getting many files from the same server will not do multiple connects / handshakes. This improves speed. Of course this is only done on files specified on a single command line and cannot be used between separate curl invokes.

Wondered could this be done with electron fetch or any other fetch libraries somehow ?

Thanks

**Comment by arantes555** [comment]
Hello @btargac,

Long answer:
Basically, what you are asking about is natively included in HTTP2. However, "fetch" is higher level. This is managed at a lower level by the HTTP library, in the case if electron-fetch it's electron's "net" API, which is in turn based on the chromium network stack. I believe the choice of protocol and re-use of TCP connections is handled correctly there. If course, it should be the same in the native browser "fetch". In any case, electron-fetch cannot do anything about this, as it's literally 2 levels of abstraction lower :)

Short answer:
It should be automatic, you should not have to worry about this.
