### ISSUE TITLE
Overriding Origin header in defaultSession causes Electron to crash

### ISSUE THREAD

**Issue by timfish** [arantes555/electron-fetch#16]
See [this issue](https://github.com/getsentry/sentry-electron/issues/176).

The gist of it is that if you're overriding the `Origin` header like this:
```typescript
app.on('ready', () => {
  session.defaultSession.webRequest.onBeforeSendHeaders(
    (details: any, callback: any) => {
      details.requestHeaders.Origin = 'www.some-random-origin.com';
      callback({ cancel: false, requestHeaders: details.requestHeaders });
    }
  );
});
```

Calling `electron-fetch@1.2/3` with Electron v2 cases a crash:
```
const response = await fetch(url, { method: 'POST', body });
```

**Comment by timfish** [comment]
Confirmed this is still an issue in `electron@5.0.6` but appears fixed in `electron@6.0.0-beta.13`

Here is the native stack trace from `5.0.5`:
https://sentry.io/share/issue/28bad86aacec4962ac119b078b874f43/

**Comment by arantes555** [comment]
@timfish looking at your stacktrace (or even just the description), it appears to be a bug in electron's `net` module (not very surprising, I have found and reported a few of those myself.. including the one which made me switch to `defaultSession` by default : https://github.com/electron/electron/issues/13587 ). 

I suggest opening a bug report on electron's project.

You could try to work around the bug by passing another session to electron-fetch.

Sorry but there does not seem to be anything I can do on electron-fetch's side :/

**Comment by timfish** [comment]
> it appears to be a bug in electron's net module

Indeed it does! If it existed in `6.0.0-beta.13` I would take the time to report it upstream to Electron but as it appears to be fixed there and in the latest `7-nightly` so probably not worth the effort.

@arantes555 leave this open in case anyone else encounters this?

**Comment by arantes555** [comment]
@timfish Yes, leaving this open for the moment, at least until 6 is released for good. Thanks for your testing !

(btw if you want to be even more thorough, or are just curious, you could try triggering the bug without electron-fetch, just doing a `net` request after setting `onBeforeSendHeaders`)
