### ISSUE TITLE
when using fetch in renderer process then it is giving me errors 

### ISSUE THREAD

**Issue by jordanhimanshu** [arantes555/electron-fetch#22]
C:\Electron\Fetch_Data\node_modules\electron-fetch\lib\index.js:1279 Uncaught TypeError: Cannot read property 'isReady' of undefined
    at Object.<anonymous> (C:\Electron\Fetch_Data\node_modules\electron-fetch\lib\index.js:1279)
    at Object.<anonymous> (C:\Electron\Fetch_Data\node_modules\electron-fetch\lib\index.js:1499)
    at Module._compile (internal/modules/cjs/loader.js:968)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986)
    at Module.load (internal/modules/cjs/loader.js:816)
    at Module._load (internal/modules/cjs/loader.js:728)
    at Module._load (electron/js2c/asar.js:717)
    at Function.Module._load (electron/js2c/asar.js:717)
    at Module.require (internal/modules/cjs/loader.js:853)
    at require (internal/modules/cjs/helpers.js:74)

this is the error i am getting because i am calling "const fetch=require('electron-fetch').default"
in the renderer. please help me i have tried many solutions but nothing is working.

and i have tried calling the native fetch() without "require" then it is working only for GET method and in other it is giving 403 error.

**Comment by arantes555** [comment]
@jordanhimanshu You are not supposed to use electron-fetch in the renderer process.

It's made to reproduce fetch functionality in the background process. In the renderer, you can just use the native fetch.

If you are absolutely totally 100% convinced you *need* electron-fetch in the renderer process and the normal fetch would not do for your pruposes, you can use `remote.require` ( https://www.electronjs.org/docs/api/remote#remoterequiremodule ) instead of the normal require.

**Comment by jordanhimanshu** [comment]
look at this code:
saveBtn.addEventListener('click',function(){
    
    const body={firstName:'Him',lastName:'Masih',email:'him@gmail.com'}
    fetch('http://localhost:8080/api/employees',{
        method:'POST',
        headers:{'content-type':'application/json'},
        mode:'cors'
    })
    .then(res=>res.json())
    .then(json=>console.log(json))

})


here i have used native fetch,then i am getting this error:
index.js:27 POST http://localhost:8080/api/employees 403
(anonymous) @ index.js:27
index.html:1 Uncaught (in promise) SyntaxError: Unexpected token I in JSON at position 0


Native fetch is working fine only for GET method

**Comment by arantes555** [comment]
@jordanhimanshu these seem to me most likely to be CSRF errors, or something like it, depending on precisely which protection measures the API implements. In any case, I really don't see how using electron-fetch will help, it will most probably fail in the same way.

**Comment by jordanhimanshu** [comment]
@arantes555 Actually i have used 'electron-fetch' with same api in main process and it is running very well with all methods but, in renderer it fails.

**Comment by jordanhimanshu** [comment]
i got a solution use 'node-fetch' , it will run properly without giving any CORS error and with PUT or POST method also.
https://github.com/node-fetch/node-fetch
