### ISSUE TITLE
v1.7.0 made "signal" option required in TS declaration file - please make it optional

### ISSUE THREAD

**Issue by welljsjs** [arantes555/electron-fetch#27]
In v1.7.0, you've introduced the `signal` parameter as part of the `RequestInit` interface. This property is marked as required in the `index.d.ts` declaration file:
[`v1.6.0...v1.7.0`](https://github.com/arantes555/electron-fetch/compare/v1.6.0...v1.7.0#diff-b52768974e6bc0faccb7d4b75b162c99R92)

Please make it optional.

**Comment by arantes555** [comment]
@welljsjs Good catch. Sorry about that. v1.7.1 is now released with this fixed
