### ISSUE TITLE
checkInvalidHeaderChar throws if header contains emoji

### ISSUE THREAD

**Issue by ilias-t** [arantes555/electron-fetch#29]
Test with `https://icanhazip.com/` which throws `TypeError: 🦆 is not a legal HTTP header value` given it contains a header `x-duck: 🦆`

Version: 1.4.0

**Comment by ilias-t** [comment]
Given `await fetch(url, { timeout: 5000 })` it also appears the Promise is never rejected so the await never resolves.

**Comment by arantes555** [comment]
That is an ... interesting problem 🤨 

I'll see what the spec says. Not sure if the TypeError itself is wanted behaviour or not.

About the orphaned promise, there were a few cases that caused this behaviour when I forked, I thought I had cleaned them all up, apparently not -_-

Can you give the electron version you tried with ? Thanks

**Comment by ilias-t** [comment]
Sure thing, Electron v9.3.0

**Comment by wheezard** [comment]
@arantes555, it seems like this is the same issue we resolved in #47. I guess this issue should be closed now?

**Comment by arantes555** [comment]
Good diagnoses @wheezard ! Closing
