### ISSUE TITLE
TypeScript & esbuild try to resolve 'electron' even not in electron

### ISSUE THREAD

**Issue by RoyTimes** [arantes555/electron-fetch#36]
The error below was thrown when building with esbuild on non-electron env

```
 > node_modules/electron-fetch/lib/index.js:1291:21: error: Could not resolve "electro
n" (mark it as external to exclude it from the bundle, or surround it with try/catch t
o handle the failure at run-time)
    1291 │   electron = require('electron');
         ╵                      ~~~~~~~~~~
```
&& 

```
> console.log(process.versions.electron)
undefined
undefined
```

I wonder if you could wrap it in a try...catch.

**Comment by arantes555** [comment]
Hello @RoyTimes 

The `require` in question should already be warded to only be called if `process.versions.electron` is truthy.

If you are not on electron, why are you using electron-fetch? Or is your built file supposed to be able to run both on electron and on node? In any case, I thing you could "mark it as external", as the `electron` module is never supposed to be bundled.

If you can explain more about your setup, maybe we can find another solution. If you are sure that there needs to be a change in electron-fetch, could you provide me with a minimal repo that reproduces this issue ? I am not familiar with esbuild

**Comment by RoyTimes** [comment]
Thanks for the reply. 

I was intent to build for browser and `electron-fetch` was not included intentionally. By yarn.lock, I think it was included by [ipfs-utils](https://github.com/ipfs/js-ipfs-utils/blob/master/package.json). 

So: 
1. Frankly, I'm not familiar with esbuild as well. The code runs well but returns error when bundling. I guess the first step is for me to switch over to Webpack. It's likely that esbuild treat the conditioning of the `require` differently. 
2. If the error remains: I'll raise an issue on ipfs-utils. 
3. If none of these works: I'll make a repo to reproduce and share it with you. 

I understand that this is most likely not related to electron-fetch at all. So I'll leave you alone for now but might come back later when I have a better understanding of the issue. : )

**Comment by arantes555** [comment]
@RoyTimes Allright, I'll leave the issue open for the moment. Don't hesitate to let me know here if it got solved another way, or if you didn't manage to fix it.

In any case, I want to reiterate my suggestion to mark "electron" as external. With most builders, it's something you gotta do.

**Comment by RoyTimes** [comment]
Webpack solves it somehow. Closing.
