### ISSUE TITLE
Named pipe support on Windows?

### ISSUE THREAD

**Issue by gbraad** [arantes555/electron-fetch#37]
I have tried your library from a very basic test with Fiddle, and a backend that runs an HTTP API over named pipes on Windows (golang); So far, I have only been able to use `got` to work: https://github.com/code-ready/crc/issues/2618 but would prefer to use the Fetch API. What might I be missing?

**Comment by arantes555** [comment]
I have never tried named pipes on electron-fetch. However, electron-fetch uses the Chromium network stack, so it depends on whether or not Chrome would support it. (Most other http requests packages use the Node network stack).

From a quick web search, it seems some people claim chrome can access named pipes with a URL like `file://./pipe/` ( https://stackoverflow.com/questions/9474276/chrome-plugin-accessing-named-pipes-on-windows/42582390 ).

In any case, I cannot do anything to support it on electron-fetch's side, as it would need to be supported by chromium first, then electron, then electron-fetch.

**Comment by gbraad** [comment]
I'll try to use the alternative URL and let's you know if this work.

**Comment by gbraad** [comment]
> electron-fetch uses the Chromium network stack

you mean Electron's `net` library?

**Comment by arantes555** [comment]
Yes, electron-fetch uses electron's net library, which uses the Chromium
network stack.

Le sam. 31 juil. 2021 à 05:23, Gerard Braad ***@***.***> a
écrit :

**Comment by gbraad** [comment]
which seems like a limitation in the chromium stack. Closing for now. Will try some more, but likely doesn't support this. Thanks

**Comment by arantes555** [comment]
You could also try passing `useElectronNet: false` to force electron-fetch
using NodeJS network stack, or try node-fetch
