### ISSUE TITLE
Consider using undici?

### ISSUE THREAD

**Issue by ronag** [arantes555/electron-fetch#43]
Undici now has a spec compliant fetch implementation: https://www.npmjs.com/package/undici

However, currently it would be a breaking change as undici, unlike node-fetch, returns web streams instead of node streams.

**Comment by Blue-Skyer** [comment]
Hello, 

We notice that ronag (https://github.com/ronag) proposed API, but the code relies on the project (https://www.npmjs.com/package/undici), in which ronag is one of the collaborators. We would like to highlight this as a distasteful "self-promotion" (promoting the use of a project without mentioning that ronag is associated with the project).

Regards, Blue Skyer.
