### ISSUE TITLE
FetchError typings: special case for 'system'

### ISSUE THREAD

**Issue by mwhitworth** [arantes555/electron-fetch#48]
Based on the logic in [fetch-error](https://github.com/arantes555/electron-fetch/blob/master/src/fetch-error.js#L16) the `type` is `system`, the `code` member is no longer a `number` but a `string`

**Comment by arantes555** [comment]
It appears you are correct, it was an error introduced in https://github.com/arantes555/electron-fetch/pull/45. Did you encounter any code-path where the `code` could be a number, or is it always a string ? From the quick glance I took, it seems to always be a string.

**Comment by mwhitworth** [comment]
Yes - it appears to always be a `string`

**Comment by arantes555** [comment]
Fixed in https://github.com/arantes555/electron-fetch/commit/69693ac4e75e3fcd8d2c0c7265600bcefa9ff2eb and released in v1.9.1
