### ISSUE TITLE
Does not work in render thread

### ISSUE THREAD

**Issue by MacroChip** [arantes555/electron-fetch#5]
https://github.com/arantes555/electron-fetch/blob/ee14e5aa4cfee929be041452f55509c40e707014/src/index.js#L22

`require("electron")` then calling `isReady` does not work in a render thread. I tried to fix this by changing it to `require("electron").remote` but then it errors out when a request finishes.

**Comment by tex0l** [comment]
@MacroChip if I may ask, why do use `electron-fetch` in a renderer process where you could simply use `window.fetch`?

**Comment by MacroChip** [comment]
I thought that I needed the `partition` option of `electron-fetch`. Does `window.fetch` use the cookies from the partition it is called in?

**Comment by tex0l** [comment]
In theory, the `window.fetch` should use the `Session` or `partition` given in the BrowserWindow constructor under (respectively) `webPreferences.session` or `webPreferences.partition`, see https://electronjs.org/docs/api/browser-window#new-browserwindowoptions.

**Comment by MacroChip** [comment]
That makes sense but I couldn't get it to work. Could be my fault or it could be due to https://github.com/electron/electron/issues/8891 in which case many libraries would have problems with cookies if they use net.request. Thanks

**Comment by tex0l** [comment]
Ok I see why you want to use `electron-fetch` then.
If you only handle JSON payloads , you couldactually import `electron-fetch` in the main process and use the electron IPC, and handle cookies manually with tough-cookie like @arantes555 suggested here https://github.com/arantes555/electron-fetch/issues/3.

**Comment by arantes555** [comment]
@MacroChip electron `net` module is only available in the main process ( https://electronjs.org/docs/api/net ), so there's no way to make electron-fetch directly usable in a renderer process. However, it should be simple enough to get it with `remote.require` ( https://electronjs.org/docs/api/remote#remoterequiremodule ). Could that work for you ?

**Comment by arantes555** [comment]
Inactive, I'm closing.
